import * as vscode from 'vscode';
import * as utils from './utils';

interface NamedColor {
    name: string;
    value: string;
    /**
     * A color that contrasts well with this color,
     * so that the name is visible against the background.
     */
    contrast: string;
}

/** Colors with string-names in CSS */
export const namedColors: NamedColor[] = [
    { name: "Red", value: "red", contrast: "black" },
    { name: "Orange", value: "orange", contrast: "black" },
    { name: "Yellow", value: "yellow", contrast: "black" },
];

/** All named colors, even if they don't have string names in CSS */
export const commonColors: NamedColor[] = [
    { name: "Black (W3C)", value: "#000000", contrast: "black" },
    { name: "Night", value: "#0C090A", contrast: "black" },
    { name: "Charcoal", value: "#34282C", contrast: "black" },
    { name: "Oil", value: "#3B3131", contrast: "black" },
    { name: "Dark Gray", value: "#3A3B3C", contrast: "black" },
    { name: "Light Black", value: "#454545", contrast: "black" },
    { name: "Black Cat", value: "#413839", contrast: "black" },
    { name: "Iridium", value: "#3D3C3A", contrast: "black" },
    { name: "Black Eel", value: "#463E3F", contrast: "black" },
    { name: "Black Cow", value: "#4C4646", contrast: "black" },
    { name: "Gray Wolf", value: "#504A4B", contrast: "black" },
    { name: "Vampire Gray", value: "#565051", contrast: "black" },
    { name: "Iron Gray", value: "#52595D", contrast: "black" },
    { name: "Gray Dolphin", value: "#5C5858", contrast: "black" },
    { name: "Carbon Gray", value: "#625D5D", contrast: "black" },
    { name: "Ash Gray", value: "#666362", contrast: "black" },
    { name: "DimGray or DimGrey (W3C)", value: "#696969", contrast: "black" },
    { name: "Nardo Gray", value: "#686A6C", contrast: "black" },
    { name: "Cloudy Gray", value: "#6D6968", contrast: "black" },
    { name: "Smokey Gray", value: "#726E6D", contrast: "black" },
    { name: "Alien Gray", value: "#736F6E", contrast: "black" },
    { name: "Sonic Silver", value: "#757575", contrast: "black" },
    { name: "Platinum Gray", value: "#797979", contrast: "black" },
    { name: "Granite", value: "#837E7C", contrast: "black" },
    { name: "Gray or Grey (W3C)", value: "#808080", contrast: "black" },
    { name: "Battleship Gray", value: "#848482", contrast: "black" },
    { name: "Gunmetal Gray", value: "#8D918D", contrast: "black" },
    { name: "DarkGray or DarkGrey (W3C)", value: "#A9A9A9", contrast: "black" },
    { name: "Gray Cloud", value: "#B6B6B4", contrast: "black" },
    { name: "Silver (W3C)", value: "#C0C0C0", contrast: "black" },
    { name: "Pale Silver", value: "#C9C0BB", contrast: "black" },
    { name: "Gray Goose", value: "#D1D0CE", contrast: "black" },
    { name: "Platinum Silver", value: "#CECECE", contrast: "black" },
    { name: "LightGray or LightGrey (W3C)", value: "#D3D3D3", contrast: "black" },
    { name: "Silver White", value: "#DADBDD", contrast: "black" },
    { name: "Gainsboro (W3C)", value: "#DCDCDC", contrast: "black" },
    { name: "Platinum", value: "#E5E4E2", contrast: "black" },
    { name: "Metallic Silver", value: "#BCC6CC", contrast: "black" },
    { name: "Blue Gray", value: "#98AFC7", contrast: "black" },
    { name: "Roman Silver", value: "#838996", contrast: "black" },
    { name: "LightSlateGray or LightSlateGrey (W3C)", value: "#778899", contrast: "black" },
    { name: "SlateGray or SlateGrey (W3C)", value: "#708090", contrast: "black" },
    { name: "Rat Gray", value: "#6D7B8D", contrast: "black" },
    { name: "Slate Granite Gray", value: "#657383", contrast: "black" },
    { name: "Jet Gray", value: "#616D7E", contrast: "black" },
    { name: "Mist Blue", value: "#646D7E", contrast: "black" },
    { name: "Marble Blue", value: "#566D7E", contrast: "black" },
    { name: "Slate Blue Grey", value: "#737CA1", contrast: "black" },
    { name: "Light Purple Blue", value: "#728FCE", contrast: "black" },
    { name: "Azure Blue", value: "#4863A0", contrast: "black" },
    { name: "Blue Jay", value: "#2B547E", contrast: "black" },
    { name: "Charcoal Blue", value: "#36454F", contrast: "black" },
    { name: "Dark Blue Grey", value: "#29465B", contrast: "black" },
    { name: "Dark Slate", value: "#2B3856", contrast: "black" },
    { name: "Deep-Sea Blue", value: "#123456", contrast: "black" },
    { name: "Night Blue", value: "#151B54", contrast: "black" },
    { name: "MidnightBlue (W3C)", value: "#191970", contrast: "black" },
    { name: "Navy (W3C)", value: "#000080", contrast: "black" },
    { name: "Denim Dark Blue", value: "#151B8D", contrast: "black" },
    { name: "DarkBlue (W3C)", value: "#00008B", contrast: "black" },
    { name: "Lapis Blue", value: "#15317E", contrast: "black" },
    { name: "New Midnight Blue", value: "#0000A0", contrast: "black" },
    { name: "Earth Blue", value: "#0000A5", contrast: "black" },
    { name: "Cobalt Blue", value: "#0020C2", contrast: "black" },
    { name: "MediumBlue (W3C)", value: "#0000CD", contrast: "black" },
    { name: "Blueberry Blue", value: "#0041C2", contrast: "black" },
    { name: "Canary Blue", value: "#2916F5", contrast: "black" },
    { name: "Blue (W3C)", value: "#0000FF", contrast: "black" },
    { name: "Samco Blue", value: "#0002FF", contrast: "black" },
    { name: "Bright Blue", value: "#0909FF", contrast: "black" },
    { name: "Blue Orchid", value: "#1F45FC", contrast: "black" },
    { name: "Sapphire Blue", value: "#2554C7", contrast: "black" },
    { name: "Blue Eyes", value: "#1569C7", contrast: "black" },
    { name: "Bright Navy Blue", value: "#1974D2", contrast: "black" },
    { name: "Balloon Blue", value: "#2B60DE", contrast: "black" },
    { name: "RoyalBlue (W3C)", value: "#4169E1", contrast: "black" },
    { name: "Ocean Blue", value: "#2B65EC", contrast: "black" },
    { name: "Blue Ribbon", value: "#306EFF", contrast: "black" },
    { name: "Blue Dress", value: "#157DEC", contrast: "black" },
    { name: "Neon Blue", value: "#1589FF", contrast: "black" },
    { name: "DodgerBlue (W3C)", value: "#1E90FF", contrast: "black" },
    { name: "Glacial Blue Ice", value: "#368BC1", contrast: "black" },
    { name: "SteelBlue (W3C)", value: "#4682B4", contrast: "black" },
    { name: "Silk Blue", value: "#488AC7", contrast: "black" },
    { name: "Windows Blue", value: "#357EC7", contrast: "black" },
    { name: "Blue Ivy", value: "#3090C7", contrast: "black" },
    { name: "Blue Koi", value: "#659EC7", contrast: "black" },
    { name: "Columbia Blue", value: "#87AFC7", contrast: "black" },
    { name: "Baby Blue", value: "#95B9C7", contrast: "black" },
    { name: "CornflowerBlue (W3C)", value: "#6495ED", contrast: "black" },
    { name: "Sky Blue Dress", value: "#6698FF", contrast: "black" },
    { name: "Iceberg", value: "#56A5EC", contrast: "black" },
    { name: "Butterfly Blue", value: "#38ACEC", contrast: "black" },
    { name: "DeepSkyBlue (W3C)", value: "#00BFFF", contrast: "black" },
    { name: "Midday Blue", value: "#3BB9FF", contrast: "black" },
    { name: "Crystal Blue", value: "#5CB3FF", contrast: "black" },
    { name: "Denim Blue", value: "#79BAEC", contrast: "black" },
    { name: "Day Sky Blue", value: "#82CAFF", contrast: "black" },
    { name: "LightSkyBlue (W3C)", value: "#87CEFA", contrast: "black" },
    { name: "SkyBlue (W3C)", value: "#87CEEB", contrast: "black" },
    { name: "Jeans Blue", value: "#A0CFEC", contrast: "black" },
    { name: "Blue Angel", value: "#B7CEEC", contrast: "black" },
    { name: "Pastel Blue", value: "#B4CFEC", contrast: "black" },
    { name: "Light Day Blue", value: "#ADDFFF", contrast: "black" },
    { name: "Sea Blue", value: "#C2DFFF", contrast: "black" },
    { name: "Heavenly Blue", value: "#C6DEFF", contrast: "black" },
    { name: "Robin Egg Blue", value: "#BDEDFF", contrast: "black" },
    { name: "PowderBlue (W3C)", value: "#B0E0E6", contrast: "black" },
    { name: "Coral Blue", value: "#AFDCEC", contrast: "black" },
    { name: "LightBlue (W3C)", value: "#ADD8E6", contrast: "black" },
    { name: "LightSteelBlue (W3C)", value: "#B0CFDE", contrast: "black" },
    { name: "Gulf Blue", value: "#C9DFEC", contrast: "black" },
    { name: "Pastel Light Blue", value: "#D5D6EA", contrast: "black" },
    { name: "Lavender Blue", value: "#E3E4FA", contrast: "black" },
    { name: "White Blue", value: "#DBE9FA", contrast: "black" },
    { name: "Lavender (W3C)", value: "#E6E6FA", contrast: "black" },
    { name: "Water", value: "#EBF4FA", contrast: "black" },
    { name: "AliceBlue (W3C)", value: "#F0F8FF", contrast: "black" },
    { name: "GhostWhite (W3C)", value: "#F8F8FF", contrast: "black" },
    { name: "Azure (W3C)", value: "#F0FFFF", contrast: "black" },
    { name: "LightCyan (W3C)", value: "#E0FFFF", contrast: "black" },
    { name: "Light Slate", value: "#CCFFFF", contrast: "black" },
    { name: "Electric Blue", value: "#9AFEFF", contrast: "black" },
    { name: "Tron Blue", value: "#7DFDFE", contrast: "black" },
    { name: "Blue Zircon", value: "#57FEFF", contrast: "black" },
    { name: "Aqua or Cyan (W3C)", value: "#00FFFF", contrast: "black" },
    { name: "Bright Cyan", value: "#0AFFFF", contrast: "black" },
    { name: "Celeste", value: "#50EBEC", contrast: "black" },
    { name: "Blue Diamond", value: "#4EE2EC", contrast: "black" },
    { name: "Bright Turquoise", value: "#16E2F5", contrast: "black" },
    { name: "Blue Lagoon", value: "#8EEBEC", contrast: "black" },
    { name: "PaleTurquoise (W3C)", value: "#AFEEEE", contrast: "black" },
    { name: "Pale Blue Lily", value: "#CFECEC", contrast: "black" },
    { name: "Light Teal", value: "#B3D9D9", contrast: "black" },
    { name: "Tiffany Blue", value: "#81D8D0", contrast: "black" },
    { name: "Blue Hosta", value: "#77BFC7", contrast: "black" },
    { name: "Cyan Opaque", value: "#92C7C7", contrast: "black" },
    { name: "Northern Lights Blue", value: "#78C7C7", contrast: "black" },
    { name: "Blue Green", value: "#7BCCB5", contrast: "black" },
    { name: "MediumAquaMarine (W3C)", value: "#66CDAA", contrast: "black" },
    { name: "Magic Mint", value: "#AAF0D1", contrast: "black" },
    { name: "Light Aquamarine", value: "#93FFE8", contrast: "black" },
    { name: "Aquamarine (W3C)", value: "#7FFFD4", contrast: "black" },
    { name: "Bright Teal", value: "#01F9C6", contrast: "black" },
    { name: "Turquoise (W3C)", value: "#40E0D0", contrast: "black" },
    { name: "MediumTurquoise (W3C)", value: "#48D1CC", contrast: "black" },
    { name: "Deep Turquoise", value: "#48CCCD", contrast: "black" },
    { name: "Jellyfish", value: "#46C7C7", contrast: "black" },
    { name: "Blue Turquoise", value: "#43C6DB", contrast: "black" },
    { name: "DarkTurquoise (W3C)", value: "#00CED1", contrast: "black" },
    { name: "Macaw Blue Green", value: "#43BFC7", contrast: "black" },
    { name: "LightSeaGreen (W3C)", value: "#20B2AA", contrast: "black" },
    { name: "Seafoam Green", value: "#3EA99F", contrast: "black" },
    { name: "CadetBlue (W3C)", value: "#5F9EA0", contrast: "black" },
    { name: "Deep-Sea", value: "#3B9C9C", contrast: "black" },
    { name: "DarkCyan (W3C)", value: "#008B8B", contrast: "black" },
    { name: "Teal Green", value: "#00827F", contrast: "black" },
    { name: "Teal (W3C)", value: "#008080", contrast: "black" },
    { name: "Teal Blue", value: "#007C80", contrast: "black" },
    { name: "Medium Teal", value: "#045F5F", contrast: "black" },
    { name: "Dark Teal", value: "#045D5D", contrast: "black" },
    { name: "Deep Teal", value: "#033E3E", contrast: "black" },
    { name: "DarkSlateGray or DarkSlateGrey (W3C)", value: "#25383C", contrast: "black" },
    { name: "Gunmetal", value: "#2C3539", contrast: "black" },
    { name: "Blue Moss Green", value: "#3C565B", contrast: "black" },
    { name: "Beetle Green", value: "#4C787E", contrast: "black" },
    { name: "Grayish Turquoise", value: "#5E7D7E", contrast: "black" },
    { name: "Greenish Blue", value: "#307D7E", contrast: "black" },
    { name: "Aquamarine Stone", value: "#348781", contrast: "black" },
    { name: "Sea Turtle Green", value: "#438D80", contrast: "black" },
    { name: "Dull-Sea Green", value: "#4E8975", contrast: "black" },
    { name: "Dark Green Blue", value: "#1F6357", contrast: "black" },
    { name: "Deep-Sea Green", value: "#306754", contrast: "black" },
    { name: "Bottle Green", value: "#006A4E", contrast: "black" },
    { name: "SeaGreen (W3C)", value: "#2E8B57", contrast: "black" },
    { name: "Elf Green", value: "#1B8A6B", contrast: "black" },
    { name: "Dark Mint", value: "#31906E", contrast: "black" },
    { name: "Jade", value: "#00A36C", contrast: "black" },
    { name: "Earth Green", value: "#34A56F", contrast: "black" },
    { name: "Chrome Green", value: "#1AA260", contrast: "black" },
    { name: "Emerald", value: "#50C878", contrast: "black" },
    { name: "Mint", value: "#3EB489", contrast: "black" },
    { name: "MediumSeaGreen (W3C)", value: "#3CB371", contrast: "black" },
    { name: "Metallic Green", value: "#7C9D8E", contrast: "black" },
    { name: "Camouflage Green", value: "#78866B", contrast: "black" },
    { name: "Sage Green", value: "#848B79", contrast: "black" },
    { name: "Hazel Green", value: "#617C58", contrast: "black" },
    { name: "Venom Green", value: "#728C00", contrast: "black" },
    { name: "OliveDrab (W3C)", value: "#6B8E23", contrast: "black" },
    { name: "Olive (W3C)", value: "#808000", contrast: "black" },
    { name: "DarkOliveGreen (W3C)", value: "#556B2F", contrast: "black" },
    { name: "Military Green", value: "#4E5B31", contrast: "black" },
    { name: "Green Leaves", value: "#3A5F0B", contrast: "black" },
    { name: "Army Green", value: "#4B5320", contrast: "black" },
    { name: "Fern Green", value: "#667C26", contrast: "black" },
    { name: "Fall Forest Green", value: "#4E9258", contrast: "black" },
    { name: "Irish Green", value: "#08A04B", contrast: "black" },
    { name: "Pine Green", value: "#387C44", contrast: "black" },
    { name: "Medium Forest Green", value: "#347235", contrast: "black" },
    { name: "Jungle Green", value: "#347C2C", contrast: "black" },
    { name: "Cactus Green", value: "#227442", contrast: "black" },
    { name: "ForestGreen (W3C)", value: "#228B22", contrast: "black" },
    { name: "Green (W3C)", value: "#008000", contrast: "black" },
    { name: "DarkGreen (W3C)", value: "#006400", contrast: "black" },
    { name: "Deep Green", value: "#056608", contrast: "black" },
    { name: "Deep Emerald Green", value: "#046307", contrast: "black" },
    { name: "Hunter Green", value: "#355E3B", contrast: "black" },
    { name: "Dark Forest Green", value: "#254117", contrast: "black" },
    { name: "Lotus Green", value: "#004225", contrast: "black" },
    { name: "Seaweed Green", value: "#437C17", contrast: "black" },
    { name: "Shamrock Green", value: "#347C17", contrast: "black" },
    { name: "Green Onion", value: "#6AA121", contrast: "black" },
    { name: "Moss Green", value: "#8A9A5B", contrast: "black" },
    { name: "Grass Green", value: "#3F9B0B", contrast: "black" },
    { name: "Green Pepper", value: "#4AA02C", contrast: "black" },
    { name: "Dark Lime Green", value: "#41A317", contrast: "black" },
    { name: "Parrot Green", value: "#12AD2B", contrast: "black" },
    { name: "Clover Green", value: "#3EA055", contrast: "black" },
    { name: "Dinosaur Green", value: "#73A16C", contrast: "black" },
    { name: "Green Snake", value: "#6CBB3C", contrast: "black" },
    { name: "Alien Green", value: "#6CC417", contrast: "black" },
    { name: "Green Apple", value: "#4CC417", contrast: "black" },
    { name: "LimeGreen (W3C)", value: "#32CD32", contrast: "black" },
    { name: "Pea Green", value: "#52D017", contrast: "black" },
    { name: "Kelly Green", value: "#4CC552", contrast: "black" },
    { name: "Zombie Green", value: "#54C571", contrast: "black" },
    { name: "Green Peas", value: "#89C35C", contrast: "black" },
    { name: "Dollar Bill Green", value: "#85BB65", contrast: "black" },
    { name: "Frog Green", value: "#99C68E", contrast: "black" },
    { name: "Turquoise Green", value: "#A0D6B4", contrast: "black" },
    { name: "DarkSeaGreen (W3C)", value: "#8FBC8F", contrast: "black" },
    { name: "Basil Green", value: "#829F82", contrast: "black" },
    { name: "Gray Green", value: "#A2AD9C", contrast: "black" },
    { name: "Iguana Green", value: "#9CB071", contrast: "black" },
    { name: "Citron Green", value: "#8FB31D", contrast: "black" },
    { name: "Acid Green", value: "#B0BF1A", contrast: "black" },
    { name: "Avocado Green", value: "#B2C248", contrast: "black" },
    { name: "Pistachio Green", value: "#9DC209", contrast: "black" },
    { name: "Salad Green", value: "#A1C935", contrast: "black" },
    { name: "YellowGreen (W3C)", value: "#9ACD32", contrast: "black" },
    { name: "Pastel Green", value: "#77DD77", contrast: "black" },
    { name: "Hummingbird Green", value: "#7FE817", contrast: "black" },
    { name: "Nebula Green", value: "#59E817", contrast: "black" },
    { name: "Stoplight Go Green", value: "#57E964", contrast: "black" },
    { name: "Neon Green", value: "#16F529", contrast: "black" },
    { name: "Jade Green", value: "#5EFB6E", contrast: "black" },
    { name: "Lime Mint Green", value: "#36F57F", contrast: "black" },
    { name: "SpringGreen (W3C)", value: "#00FF7F", contrast: "black" },
    { name: "MediumSpringGreen (W3C)", value: "#00FA9A", contrast: "black" },
    { name: "Emerald Green", value: "#5FFB17", contrast: "black" },
    { name: "Lime (W3C)", value: "#00FF00", contrast: "black" },
    { name: "LawnGreen (W3C)", value: "#7CFC00", contrast: "black" },
    { name: "Bright Green", value: "#66FF00", contrast: "black" },
    { name: "Chartreuse (W3C)", value: "#7FFF00", contrast: "black" },
    { name: "Yellow Lawn Green", value: "#87F717", contrast: "black" },
    { name: "Aloe Vera Green", value: "#98F516", contrast: "black" },
    { name: "Dull Green Yellow", value: "#B1FB17", contrast: "black" },
    { name: "Lemon Green", value: "#ADF802", contrast: "black" },
    { name: "GreenYellow (W3C)", value: "#ADFF2F", contrast: "black" },
    { name: "Chameleon Green", value: "#BDF516", contrast: "black" },
    { name: "Neon Yellow Green", value: "#DAEE01", contrast: "black" },
    { name: "Yellow Green Grosbeak", value: "#E2F516", contrast: "black" },
    { name: "Tea Green", value: "#CCFB5D", contrast: "black" },
    { name: "Slime Green", value: "#BCE954", contrast: "black" },
    { name: "Algae Green", value: "#64E986", contrast: "black" },
    { name: "LightGreen (W3C)", value: "#90EE90", contrast: "black" },
    { name: "Dragon Green", value: "#6AFB92", contrast: "black" },
    { name: "PaleGreen (W3C)", value: "#98FB98", contrast: "black" },
    { name: "Mint Green", value: "#98FF98", contrast: "black" },
    { name: "Green Thumb", value: "#B5EAAA", contrast: "black" },
    { name: "Organic Brown", value: "#E3F9A6", contrast: "black" },
    { name: "Light Jade", value: "#C3FDB8", contrast: "black" },
    { name: "Light Mint Green", value: "#C2E5D3", contrast: "black" },
    { name: "Light Rose Green", value: "#DBF9DB", contrast: "black" },
    { name: "Chrome White", value: "#E8F1D4", contrast: "black" },
    { name: "HoneyDew (W3C)", value: "#F0FFF0", contrast: "black" },
    { name: "MintCream (W3C)", value: "#F5FFFA", contrast: "black" },
    { name: "LemonChiffon (W3C)", value: "#FFFACD", contrast: "black" },
    { name: "Parchment", value: "#FFFFC2", contrast: "black" },
    { name: "Cream", value: "#FFFFCC", contrast: "black" },
    { name: "Cream White", value: "#FFFDD0", contrast: "black" },
    { name: "LightGoldenRodYellow (W3C)", value: "#FAFAD2", contrast: "black" },
    { name: "LightYellow (W3C)", value: "#FFFFE0", contrast: "black" },
    { name: "Beige (W3C)", value: "#F5F5DC", contrast: "black" },
    { name: "Cornsilk (W3C)", value: "#FFF8DC", contrast: "black" },
    { name: "Blonde", value: "#FBF6D9", contrast: "black" },
    { name: "Champagne", value: "#F7E7CE", contrast: "black" },
    { name: "AntiqueWhite (W3C)", value: "#FAEBD7", contrast: "black" },
    { name: "PapayaWhip (W3C)", value: "#FFEFD5", contrast: "black" },
    { name: "BlanchedAlmond (W3C)", value: "#FFEBCD", contrast: "black" },
    { name: "Bisque (W3C)", value: "#FFE4C4", contrast: "black" },
    { name: "Wheat (W3C)", value: "#F5DEB3", contrast: "black" },
    { name: "Moccasin (W3C)", value: "#FFE4B5", contrast: "black" },
    { name: "Peach", value: "#FFE5B4", contrast: "black" },
    { name: "Light Orange", value: "#FED8B1", contrast: "black" },
    { name: "PeachPuff (W3C)", value: "#FFDAB9", contrast: "black" },
    { name: "Coral Peach", value: "#FBD5AB", contrast: "black" },
    { name: "NavajoWhite (W3C)", value: "#FFDEAD", contrast: "black" },
    { name: "Golden Blonde", value: "#FBE7A1", contrast: "black" },
    { name: "Golden Silk", value: "#F3E3C3", contrast: "black" },
    { name: "Dark Blonde", value: "#F0E2B6", contrast: "black" },
    { name: "Light Gold", value: "#F1E5AC", contrast: "black" },
    { name: "Vanilla", value: "#F3E5AB", contrast: "black" },
    { name: "Tan Brown", value: "#ECE5B6", contrast: "black" },
    { name: "Dirty White", value: "#E8E4C9", contrast: "black" },
    { name: "PaleGoldenRod (W3C)", value: "#EEE8AA", contrast: "black" },
    { name: "Khaki (W3C)", value: "#F0E68C", contrast: "black" },
    { name: "Cardboard Brown", value: "#EDDA74", contrast: "black" },
    { name: "Harvest Gold", value: "#EDE275", contrast: "black" },
    { name: "Sun Yellow", value: "#FFE87C", contrast: "black" },
    { name: "Corn Yellow", value: "#FFF380", contrast: "black" },
    { name: "Pastel Yellow", value: "#FAF884", contrast: "black" },
    { name: "Neon Yellow", value: "#FFFF33", contrast: "black" },
    { name: "Yellow (W3C)", value: "#FFFF00", contrast: "black" },
    { name: "Canary Yellow", value: "#FFEF00", contrast: "black" },
    { name: "Banana Yellow", value: "#F5E216", contrast: "black" },
    { name: "Mustard Yellow", value: "#FFDB58", contrast: "black" },
    { name: "Golden Yellow", value: "#FFDF00", contrast: "black" },
    { name: "Bold Yellow", value: "#F9DB24", contrast: "black" },
    { name: "Rubber Ducky Yellow", value: "#FFD801", contrast: "black" },
    { name: "Gold (W3C)", value: "#FFD700", contrast: "black" },
    { name: "Bright Gold", value: "#FDD017", contrast: "black" },
    { name: "Chrome Gold", value: "#FFCE44", contrast: "black" },
    { name: "Golden Brown", value: "#EAC117", contrast: "black" },
    { name: "Deep Yellow", value: "#F6BE00", contrast: "black" },
    { name: "Macaroni and Cheese", value: "#F2BB66", contrast: "black" },
    { name: "Saffron", value: "#FBB917", contrast: "black" },
    { name: "Neon Gold", value: "#FDBD01", contrast: "black" },
    { name: "Beer", value: "#FBB117", contrast: "black" },
    { name: "Yellow Orange or Orange Yellow", value: "#FFAE42", contrast: "black" },
    { name: "Cantaloupe", value: "#FFA62F", contrast: "black" },
    { name: "Cheese Orange", value: "#FFA600", contrast: "black" },
    { name: "Orange (W3C)", value: "#FFA500", contrast: "black" },
    { name: "Brown Sand", value: "#EE9A4D", contrast: "black" },
    { name: "SandyBrown (W3C)", value: "#F4A460", contrast: "black" },
    { name: "Brown Sugar", value: "#E2A76F", contrast: "black" },
    { name: "Camel Brown", value: "#C19A6B", contrast: "black" },
    { name: "Deer Brown", value: "#E6BF83", contrast: "black" },
    { name: "BurlyWood (W3C)", value: "#DEB887", contrast: "black" },
    { name: "Tan (W3C)", value: "#D2B48C", contrast: "black" },
    { name: "Light French Beige", value: "#C8AD7F", contrast: "black" },
    { name: "Sand", value: "#C2B280", contrast: "black" },
    { name: "Sage", value: "#BCB88A", contrast: "black" },
    { name: "Fall Leaf Brown", value: "#C8B560", contrast: "black" },
    { name: "Ginger Brown", value: "#C9BE62", contrast: "black" },
    { name: "Bronze Gold", value: "#C9AE5D", contrast: "black" },
    { name: "DarkKhaki (W3C)", value: "#BDB76B", contrast: "black" },
    { name: "Olive Green", value: "#BAB86C", contrast: "black" },
    { name: "Brass", value: "#B5A642", contrast: "black" },
    { name: "Cookie Brown", value: "#C7A317", contrast: "black" },
    { name: "Metallic Gold", value: "#D4AF37", contrast: "black" },
    { name: "Bee Yellow", value: "#E9AB17", contrast: "black" },
    { name: "School Bus Yellow", value: "#E8A317", contrast: "black" },
    { name: "GoldenRod (W3C)", value: "#DAA520", contrast: "black" },
    { name: "Orange Gold", value: "#D4A017", contrast: "black" },
    { name: "Caramel", value: "#C68E17", contrast: "black" },
    { name: "DarkGoldenRod (W3C)", value: "#B8860B", contrast: "black" },
    { name: "Cinnamon", value: "#C58917", contrast: "black" },
    { name: "Peru (W3C)", value: "#CD853F", contrast: "black" },
    { name: "Bronze", value: "#CD7F32", contrast: "black" },
    { name: "Tiger Orange", value: "#C88141", contrast: "black" },
    { name: "Copper", value: "#B87333", contrast: "black" },
    { name: "Dark Gold", value: "#AA6C39", contrast: "black" },
    { name: "Metallic Bronze", value: "#A97142", contrast: "black" },
    { name: "Dark Almond", value: "#AB784E", contrast: "black" },
    { name: "Wood", value: "#966F33", contrast: "black" },
    { name: "Oak Brown", value: "#806517", contrast: "black" },
    { name: "Antique Bronze", value: "#665D1E", contrast: "black" },
    { name: "Hazel", value: "#8E7618", contrast: "black" },
    { name: "Dark Yellow", value: "#8B8000", contrast: "black" },
    { name: "Dark Moccasin", value: "#827839", contrast: "black" },
    { name: "Khaki Green", value: "#8A865D", contrast: "black" },
    { name: "Millennium Jade", value: "#93917C", contrast: "black" },
    { name: "Dark Beige", value: "#9F8C76", contrast: "black" },
    { name: "Bullet Shell", value: "#AF9B60", contrast: "black" },
    { name: "Army Brown", value: "#827B60", contrast: "black" },
    { name: "Sandstone", value: "#786D5F", contrast: "black" },
    { name: "Taupe", value: "#483C32", contrast: "black" },
    { name: "Mocha", value: "#493D26", contrast: "black" },
    { name: "Milk Chocolate", value: "#513B1C", contrast: "black" },
    { name: "Gray Brown", value: "#3D3635", contrast: "black" },
    { name: "Dark Coffee", value: "#3B2F2F", contrast: "black" },
    { name: "Old Burgundy", value: "#43302E", contrast: "black" },
    { name: "Western Charcoal", value: "#49413F", contrast: "black" },
    { name: "Bakers Brown", value: "#5C3317", contrast: "black" },
    { name: "Dark Brown", value: "#654321", contrast: "black" },
    { name: "Sepia Brown", value: "#704214", contrast: "black" },
    { name: "Dark Bronze", value: "#804A00", contrast: "black" },
    { name: "Coffee", value: "#6F4E37", contrast: "black" },
    { name: "Brown Bear", value: "#835C3B", contrast: "black" },
    { name: "Red Dirt", value: "#7F5217", contrast: "black" },
    { name: "Sepia", value: "#7F462C", contrast: "black" },
    { name: "Sienna (W3C)", value: "#A0522D", contrast: "black" },
    { name: "SaddleBrown (W3C)", value: "#8B4513", contrast: "black" },
    { name: "Dark Sienna", value: "#8A4117", contrast: "black" },
    { name: "Sangria", value: "#7E3817", contrast: "black" },
    { name: "Blood Red", value: "#7E3517", contrast: "black" },
    { name: "Chestnut", value: "#954535", contrast: "black" },
    { name: "Coral Brown", value: "#9E4638", contrast: "black" },
    { name: "Chestnut Red", value: "#C34A2C", contrast: "black" },
    { name: "Mahogany", value: "#C04000", contrast: "black" },
    { name: "Red Gold", value: "#EB5406", contrast: "black" },
    { name: "Red Fox", value: "#C35817", contrast: "black" },
    { name: "Dark Bisque", value: "#B86500", contrast: "black" },
    { name: "Light Brown", value: "#B5651D", contrast: "black" },
    { name: "Petra Gold", value: "#B76734", contrast: "black" },
    { name: "Rust", value: "#C36241", contrast: "black" },
    { name: "Copper Red", value: "#CB6D51", contrast: "black" },
    { name: "Orange Salmon", value: "#C47451", contrast: "black" },
    { name: "Chocolate (W3C)", value: "#D2691E", contrast: "black" },
    { name: "Sedona", value: "#CC6600", contrast: "black" },
    { name: "Papaya Orange", value: "#E56717", contrast: "black" },
    { name: "Halloween Orange", value: "#E66C2C", contrast: "black" },
    { name: "Neon Orange", value: "#FF6700", contrast: "black" },
    { name: "Bright Orange", value: "#FF5F1F", contrast: "black" },
    { name: "Pumpkin Orange", value: "#F87217", contrast: "black" },
    { name: "Carrot Orange", value: "#F88017", contrast: "black" },
    { name: "DarkOrange (W3C)", value: "#FF8C00", contrast: "black" },
    { name: "Construction Cone Orange", value: "#F87431", contrast: "black" },
    { name: "Indian Saffron", value: "#FF7722", contrast: "black" },
    { name: "Sunrise Orange", value: "#E67451", contrast: "black" },
    { name: "Mango Orange", value: "#FF8040", contrast: "black" },
    { name: "Coral (W3C)", value: "#FF7F50", contrast: "black" },
    { name: "Basket Ball Orange", value: "#F88158", contrast: "black" },
    { name: "Light Salmon Rose", value: "#F9966B", contrast: "black" },
    { name: "LightSalmon (W3C)", value: "#FFA07A", contrast: "black" },
    { name: "DarkSalmon (W3C)", value: "#E9967A", contrast: "black" },
    { name: "Tangerine", value: "#E78A61", contrast: "black" },
    { name: "Light Copper", value: "#DA8A67", contrast: "black" },
    { name: "Salmon Pink", value: "#FF8674", contrast: "black" },
    { name: "Salmon (W3C)", value: "#FA8072", contrast: "black" },
    { name: "Peach Pink", value: "#F98B88", contrast: "black" },
    { name: "LightCoral (W3C)", value: "#F08080", contrast: "black" },
    { name: "Pastel Red", value: "#F67280", contrast: "black" },
    { name: "Pink Coral", value: "#E77471", contrast: "black" },
    { name: "Bean Red", value: "#F75D59", contrast: "black" },
    { name: "Valentine Red", value: "#E55451", contrast: "black" },
    { name: "IndianRed (W3C)", value: "#CD5C5C", contrast: "black" },
    { name: "Tomato (W3C)", value: "#FF6347", contrast: "black" },
    { name: "Shocking Orange", value: "#E55B3C", contrast: "black" },
    { name: "OrangeRed (W3C)", value: "#FF4500", contrast: "black" },
    { name: "Red (W3C)", value: "#FF0000", contrast: "black" },
    { name: "Neon Red", value: "#FD1C03", contrast: "black" },
    { name: "Scarlet Red", value: "#FF2400", contrast: "black" },
    { name: "Ruby Red", value: "#F62217", contrast: "black" },
    { name: "Ferrari Red", value: "#F70D1A", contrast: "black" },
    { name: "Fire Engine Red", value: "#F62817", contrast: "black" },
    { name: "Lava Red", value: "#E42217", contrast: "black" },
    { name: "Love Red", value: "#E41B17", contrast: "black" },
    { name: "Grapefruit", value: "#DC381F", contrast: "black" },
    { name: "Cherry Red", value: "#C24641", contrast: "black" },
    { name: "Chilli Pepper", value: "#C11B17", contrast: "black" },
    { name: "FireBrick (W3C)", value: "#B22222", contrast: "black" },
    { name: "Tomato Sauce Red", value: "#B21807", contrast: "black" },
    { name: "Brown (W3C)", value: "#A52A2A", contrast: "black" },
    { name: "Carbon Red", value: "#A70D2A", contrast: "black" },
    { name: "Cranberry", value: "#9F000F", contrast: "black" },
    { name: "Saffron Red", value: "#931314", contrast: "black" },
    { name: "Crimson Red", value: "#990000", contrast: "black" },
    { name: "Red Wine or Wine Red", value: "#990012", contrast: "black" },
    { name: "DarkRed (W3C)", value: "#8B0000", contrast: "black" },
    { name: "Maroon (W3C)", value: "#800000", contrast: "black" },
    { name: "Burgundy", value: "#8C001A", contrast: "black" },
    { name: "Vermilion", value: "#7E191B", contrast: "black" },
    { name: "Deep Red", value: "#800517", contrast: "black" },
    { name: "Red Blood", value: "#660000", contrast: "black" },
    { name: "Blood Night", value: "#551606", contrast: "black" },
    { name: "Dark Scarlet", value: "#560319", contrast: "black" },
    { name: "Black Bean", value: "#3D0C02", contrast: "black" },
    { name: "Chocolate Brown", value: "#3F000F", contrast: "black" },
    { name: "Midnight", value: "#2B1B17", contrast: "black" },
    { name: "Purple Lily", value: "#550A35", contrast: "black" },
    { name: "Purple Maroon", value: "#810541", contrast: "black" },
    { name: "Plum Pie", value: "#7D0541", contrast: "black" },
    { name: "Plum Velvet", value: "#7D0552", contrast: "black" },
    { name: "Dark Raspberry", value: "#872657", contrast: "black" },
    { name: "Velvet Maroon", value: "#7E354D", contrast: "black" },
    { name: "Rosy-Finch", value: "#7F4E52", contrast: "black" },
    { name: "Dull Purple", value: "#7F525D", contrast: "black" },
    { name: "Puce", value: "#7F5A58", contrast: "black" },
    { name: "Rose Dust", value: "#997070", contrast: "black" },
    { name: "Pastel Brown", value: "#B1907F", contrast: "black" },
    { name: "Rosy Pink", value: "#B38481", contrast: "black" },
    { name: "RosyBrown (W3C)", value: "#BC8F8F", contrast: "black" },
    { name: "Khaki Rose", value: "#C5908E", contrast: "black" },
    { name: "Lipstick Pink", value: "#C48793", contrast: "black" },
    { name: "Pink Brown", value: "#C48189", contrast: "black" },
    { name: "Old Rose", value: "#C08081", contrast: "black" },
    { name: "Dusty Pink", value: "#D58A94", contrast: "black" },
    { name: "Pink Daisy", value: "#E799A3", contrast: "black" },
    { name: "Rose", value: "#E8ADAA", contrast: "black" },
    { name: "Dusty Rose", value: "#C9A9A6", contrast: "black" },
    { name: "Silver Pink", value: "#C4AEAD", contrast: "black" },
    { name: "Gold Pink", value: "#E6C7C2", contrast: "black" },
    { name: "Rose Gold", value: "#ECC5C0", contrast: "black" },
    { name: "Deep Peach", value: "#FFCBA4", contrast: "black" },
    { name: "Pastel Orange", value: "#F8B88B", contrast: "black" },
    { name: "Desert Sand", value: "#EDC9AF", contrast: "black" },
    { name: "Unbleached Silk", value: "#FFDDCA", contrast: "black" },
    { name: "Pig Pink", value: "#FDD7E4", contrast: "black" },
    { name: "Pale Pink", value: "#F2D4D7", contrast: "black" },
    { name: "Blush", value: "#FFE6E8", contrast: "black" },
    { name: "MistyRose (W3C)", value: "#FFE4E1", contrast: "black" },
    { name: "Pink Bubble Gum", value: "#FFDFDD", contrast: "black" },
    { name: "Light Rose", value: "#FBCFCD", contrast: "black" },
    { name: "Light Red", value: "#FFCCCB", contrast: "black" },
    { name: "Warm Pink", value: "#F6C6BD", contrast: "black" },
    { name: "Deep Rose", value: "#FBBBB9", contrast: "black" },
    { name: "Pink (W3C)", value: "#FFC0CB", contrast: "black" },
    { name: "LightPink (W3C)", value: "#FFB6C1", contrast: "black" },
    { name: "Soft Pink", value: "#FFB8BF", contrast: "black" },
    { name: "Donut Pink", value: "#FAAFBE", contrast: "black" },
    { name: "Baby Pink", value: "#FAAFBA", contrast: "black" },
    { name: "Flamingo Pink", value: "#F9A7B0", contrast: "black" },
    { name: "Pastel Pink", value: "#FEA3AA", contrast: "black" },
    { name: "Rose Pink or Pink Rose", value: "#E7A1B0", contrast: "black" },
    { name: "Cadillac Pink", value: "#E38AAE", contrast: "black" },
    { name: "Carnation Pink", value: "#F778A1", contrast: "black" },
    { name: "Pastel Rose", value: "#E5788F", contrast: "black" },
    { name: "Blush Red", value: "#E56E94", contrast: "black" },
    { name: "PaleVioletRed (W3C)", value: "#DB7093", contrast: "black" },
    { name: "Purple Pink", value: "#D16587", contrast: "black" },
    { name: "Tulip Pink", value: "#C25A7C", contrast: "black" },
    { name: "Bashful Pink", value: "#C25283", contrast: "black" },
    { name: "Dark Pink", value: "#E75480", contrast: "black" },
    { name: "Dark Hot Pink", value: "#F660AB", contrast: "black" },
    { name: "HotPink (W3C)", value: "#FF69B4", contrast: "black" },
    { name: "Watermelon Pink", value: "#FC6C85", contrast: "black" },
    { name: "Violet Red", value: "#F6358A", contrast: "black" },
    { name: "Hot Deep Pink", value: "#F52887", contrast: "black" },
    { name: "Bright Pink", value: "#FF007F", contrast: "black" },
    { name: "DeepPink (W3C)", value: "#FF1493", contrast: "black" },
    { name: "Neon Pink", value: "#F535AA", contrast: "black" },
    { name: "Chrome Pink", value: "#FF33AA", contrast: "black" },
    { name: "Neon Hot Pink", value: "#FD349C", contrast: "black" },
    { name: "Pink Cupcake", value: "#E45E9D", contrast: "black" },
    { name: "Royal Pink", value: "#E759AC", contrast: "black" },
    { name: "Dimorphotheca Magenta", value: "#E3319D", contrast: "black" },
    { name: "Pink Lemonade", value: "#E4287C", contrast: "black" },
    { name: "Red Pink", value: "#FA2A55", contrast: "black" },
    { name: "Raspberry", value: "#E30B5D", contrast: "black" },
    { name: "Crimson (W3C)", value: "#DC143C", contrast: "black" },
    { name: "Bright Maroon", value: "#C32148", contrast: "black" },
    { name: "Rose Red", value: "#C21E56", contrast: "black" },
    { name: "Rogue Pink", value: "#C12869", contrast: "black" },
    { name: "Burnt Pink", value: "#C12267", contrast: "black" },
    { name: "Pink Violet", value: "#CA226B", contrast: "black" },
    { name: "Magenta Pink", value: "#CC338B", contrast: "black" },
    { name: "MediumVioletRed (W3C)", value: "#C71585", contrast: "black" },
    { name: "Dark Carnation Pink", value: "#C12283", contrast: "black" },
    { name: "Raspberry Purple", value: "#B3446C", contrast: "black" },
    { name: "Pink Plum", value: "#B93B8F", contrast: "black" },
    { name: "Orchid (W3C)", value: "#DA70D6", contrast: "black" },
    { name: "Deep Mauve", value: "#DF73D4", contrast: "black" },
    { name: "Violet (W3C)", value: "#EE82EE", contrast: "black" },
    { name: "Fuchsia Pink", value: "#FF77FF", contrast: "black" },
    { name: "Bright Neon Pink", value: "#F433FF", contrast: "black" },
    { name: "Fuchsia or Magenta (W3C)", value: "#FF00FF", contrast: "black" },
    { name: "Crimson Purple", value: "#E238EC", contrast: "black" },
    { name: "Heliotrope Purple", value: "#D462FF", contrast: "black" },
    { name: "Tyrian Purple", value: "#C45AEC", contrast: "black" },
    { name: "MediumOrchid (W3C)", value: "#BA55D3", contrast: "black" },
    { name: "Purple Flower", value: "#A74AC7", contrast: "black" },
    { name: "Orchid Purple", value: "#B048B5", contrast: "black" },
    { name: "Rich Lilac", value: "#B666D2", contrast: "black" },
    { name: "Pastel Violet", value: "#D291BC", contrast: "black" },
    { name: "Mauve Taupe", value: "#915F6D", contrast: "black" },
    { name: "Viola Purple", value: "#7E587E", contrast: "black" },
    { name: "Eggplant", value: "#614051", contrast: "black" },
    { name: "Plum Purple", value: "#583759", contrast: "black" },
    { name: "Grape", value: "#5E5A80", contrast: "black" },
    { name: "Purple Navy", value: "#4E5180", contrast: "black" },
    { name: "SlateBlue (W3C)", value: "#6A5ACD", contrast: "black" },
    { name: "Blue Lotus", value: "#6960EC", contrast: "black" },
    { name: "Blurple", value: "#5865F2", contrast: "black" },
    { name: "Light Slate Blue", value: "#736AFF", contrast: "black" },
    { name: "MediumSlateBlue (W3C)", value: "#7B68EE", contrast: "black" },
    { name: "Periwinkle Purple", value: "#7575CF", contrast: "black" },
    { name: "Very Peri", value: "#6667AB", contrast: "black" },
    { name: "Bright Grape", value: "#6F2DA8", contrast: "black" },
    { name: "Purple Amethyst", value: "#6C2DC7", contrast: "black" },
    { name: "Bright Purple", value: "#6A0DAD", contrast: "black" },
    { name: "Deep Periwinkle", value: "#5453A6", contrast: "black" },
    { name: "DarkSlateBlue (W3C)", value: "#483D8B", contrast: "black" },
    { name: "Purple Haze", value: "#4E387E", contrast: "black" },
    { name: "Purple Iris", value: "#571B7E", contrast: "black" },
    { name: "Dark Purple", value: "#4B0150", contrast: "black" },
    { name: "Deep Purple", value: "#36013F", contrast: "black" },
    { name: "Midnight Purple", value: "#2E1A47", contrast: "black" },
    { name: "Purple Monster", value: "#461B7E", contrast: "black" },
    { name: "Indigo (W3C)", value: "#4B0082", contrast: "black" },
    { name: "Blue Whale", value: "#342D7E", contrast: "black" },
    { name: "RebeccaPurple (W3C)", value: "#663399", contrast: "black" },
    { name: "Purple Jam", value: "#6A287E", contrast: "black" },
    { name: "DarkMagenta (W3C)", value: "#8B008B", contrast: "black" },
    { name: "Purple (W3C)", value: "#800080", contrast: "black" },
    { name: "French Lilac", value: "#86608E", contrast: "black" },
    { name: "DarkOrchid (W3C)", value: "#9932CC", contrast: "black" },
    { name: "DarkViolet (W3C)", value: "#9400D3", contrast: "black" },
    { name: "Purple Violet", value: "#8D38C9", contrast: "black" },
    { name: "Jasmine Purple", value: "#A23BEC", contrast: "black" },
    { name: "Purple Daffodil", value: "#B041FF", contrast: "black" },
    { name: "Clematis Violet", value: "#842DCE", contrast: "black" },
    { name: "BlueViolet (W3C)", value: "#8A2BE2", contrast: "black" },
    { name: "Purple Sage Bush", value: "#7A5DC7", contrast: "black" },
    { name: "Lovely Purple", value: "#7F38EC", contrast: "black" },
    { name: "Neon Purple", value: "#9D00FF", contrast: "black" },
    { name: "Purple Plum", value: "#8E35EF", contrast: "black" },
    { name: "Aztech Purple", value: "#893BFF", contrast: "black" },
    { name: "MediumPurple (W3C)", value: "#9370DB", contrast: "black" },
    { name: "Light Purple", value: "#8467D7", contrast: "black" },
    { name: "Crocus Purple", value: "#9172EC", contrast: "black" },
    { name: "Purple Mimosa", value: "#9E7BFF", contrast: "black" },
    { name: "Periwinkle", value: "#CCCCFF", contrast: "black" },
    { name: "Pale Lilac", value: "#DCD0FF", contrast: "black" },
    { name: "Lavender Purple", value: "#967BB6", contrast: "black" },
    { name: "Rose Purple", value: "#B09FCA", contrast: "black" },
    { name: "Lilac", value: "#C8A2C8", contrast: "black" },
    { name: "Mauve", value: "#E0B0FF", contrast: "black" },
    { name: "Bright Lilac", value: "#D891EF", contrast: "black" },
    { name: "Purple Dragon", value: "#C38EC7", contrast: "black" },
    { name: "Plum (W3C)", value: "#DDA0DD", contrast: "black" },
    { name: "Blush Pink", value: "#E6A9EC", contrast: "black" },
    { name: "Pastel Purple", value: "#F2A2E8", contrast: "black" },
    { name: "Blossom Pink", value: "#F9B7FF", contrast: "black" },
    { name: "Wisteria Purple", value: "#C6AEC7", contrast: "black" },
    { name: "Purple Thistle", value: "#D2B9D3", contrast: "black" },
    { name: "Thistle (W3C)", value: "#D8BFD8", contrast: "black" },
    { name: "Purple White", value: "#DFD3E3", contrast: "black" },
    { name: "Periwinkle Pink", value: "#E9CFEC", contrast: "black" },
    { name: "Cotton Candy", value: "#FCDFFF", contrast: "black" },
    { name: "Lavender Pinocchio", value: "#EBDDE2", contrast: "black" },
    { name: "Dark White", value: "#E1D9D1", contrast: "black" },
    { name: "Ash White", value: "#E9E4D4", contrast: "black" },
    { name: "White Chocolate", value: "#EDE6D6", contrast: "black" },
    { name: "Soft Ivory", value: "#FAF0DD", contrast: "black" },
    { name: "Off White", value: "#F8F0E3", contrast: "black" },
    { name: "Pearl White", value: "#F8F6F0", contrast: "black" },
    { name: "Red White", value: "#F3E8EA", contrast: "black" },
    { name: "LavenderBlush (W3C)", value: "#FFF0F5", contrast: "black" },
    { name: "Pearl", value: "#FDEEF4", contrast: "black" },
    { name: "Egg Shell", value: "#FFF9E3", contrast: "black" },
    { name: "OldLace (W3C)", value: "#FEF0E3", contrast: "black" },
    { name: "Linen (W3C)", value: "#FAF0E6", contrast: "black" },
    { name: "SeaShell (W3C)", value: "#FFF5EE", contrast: "black" },
    { name: "Bone White", value: "#F9F6EE", contrast: "black" },
    { name: "Rice", value: "#FAF5EF", contrast: "black" },
    { name: "FloralWhite (W3C)", value: "#FFFAF0", contrast: "black" },
    { name: "Ivory (W3C)", value: "#FFFFF0", contrast: "black" },
    { name: "White Gold", value: "#FFFFF4", contrast: "black" },
    { name: "Light White", value: "#FFFFF7", contrast: "black" },
    { name: "WhiteSmoke (W3C)", value: "#F5F5F5", contrast: "black" },
    { name: "Cotton", value: "#FBFBF9", contrast: "black" },
    { name: "Snow (W3C)", value: "#FFFAFA", contrast: "black" },
    { name: "Milk White", value: "#FEFCFF", contrast: "black" },
    { name: "Half White", value: "#FFFEFA", contrast: "black" },
    { name: "White (W3C)", value: "#FFFFFF", contrast: "black" },
];

/** User-chosen favorites (will be stored in a config json) */
export let favoriteColors: NamedColor[] = [];

export class PaletteProvider implements vscode.WebviewViewProvider {
    constructor(
        private title: string,
        private colorList: NamedColor[],
    ) { }

    resolveWebviewView(
        webviewView: vscode.WebviewView,
        context: vscode.WebviewViewResolveContext,
        token: vscode.CancellationToken
    ): Thenable<void> | void {
        webviewView.title = this.title;
        webviewView.webview.html = `
<!DOCTYPE html>
<html>
<head>
    <style>
        /* todo */
        .palette-item {
            padding: 10px;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    <div>
        ${this.colorList.map((e: NamedColor) => `<div class="palette-item" style="background-color:${e.value};color:${e.contrast}">${e.name}</div>`).join('\n')}
    </div>
</body>
</html>`;
    }
}
