import { NamedColor } from "../hw/palette";
export default [
    { name: "Black (W3C)", value: "#000000" },
    { name: "Night", value: "#0C090A" },
    { name: "Charcoal", value: "#34282C" },
    { name: "Oil", value: "#3B3131" },
    { name: "Dark Gray", value: "#3A3B3C" },
    { name: "Light Black", value: "#454545" },
    { name: "Black Cat", value: "#413839" },
    { name: "Iridium", value: "#3D3C3A" },
    { name: "Black Eel", value: "#463E3F" },
    { name: "Black Cow", value: "#4C4646" },
    { name: "Gray Wolf", value: "#504A4B" },
    { name: "Vampire Gray", value: "#565051" },
    { name: "Iron Gray", value: "#52595D" },
    { name: "Gray Dolphin", value: "#5C5858" },
    { name: "Carbon Gray", value: "#625D5D" },
    { name: "Ash Gray", value: "#666362" },
    { name: "DimGray or DimGrey (W3C)", value: "#696969" },
    { name: "Nardo Gray", value: "#686A6C" },
    { name: "Cloudy Gray", value: "#6D6968" },
    { name: "Smokey Gray", value: "#726E6D" },
    { name: "Alien Gray", value: "#736F6E" },
    { name: "Sonic Silver", value: "#757575" },
    { name: "Platinum Gray", value: "#797979" },
    { name: "Granite", value: "#837E7C" },
    { name: "Gray or Grey (W3C)", value: "#808080" },
    { name: "Battleship Gray", value: "#848482" },
    { name: "Gunmetal Gray", value: "#8D918D" },
    { name: "DarkGray or DarkGrey (W3C)", value: "#A9A9A9" },
    { name: "Gray Cloud", value: "#B6B6B4" },
    { name: "Silver (W3C)", value: "#C0C0C0" },
    { name: "Pale Silver", value: "#C9C0BB" },
    { name: "Gray Goose", value: "#D1D0CE" },
    { name: "Platinum Silver", value: "#CECECE" },
    { name: "LightGray or LightGrey (W3C)", value: "#D3D3D3" },
    { name: "Silver White", value: "#DADBDD" },
    { name: "Gainsboro (W3C)", value: "#DCDCDC" },
    { name: "Platinum", value: "#E5E4E2" },
    { name: "Metallic Silver", value: "#BCC6CC" },
    { name: "Blue Gray", value: "#98AFC7" },
    { name: "Roman Silver", value: "#838996" },
    { name: "LightSlateGray or LightSlateGrey (W3C)", value: "#778899" },
    { name: "SlateGray or SlateGrey (W3C)", value: "#708090" },
    { name: "Rat Gray", value: "#6D7B8D" },
    { name: "Slate Granite Gray", value: "#657383" },
    { name: "Jet Gray", value: "#616D7E" },
    { name: "Mist Blue", value: "#646D7E" },
    { name: "Marble Blue", value: "#566D7E" },
    { name: "Slate Blue Grey", value: "#737CA1" },
    { name: "Light Purple Blue", value: "#728FCE" },
    { name: "Azure Blue", value: "#4863A0" },
    { name: "Blue Jay", value: "#2B547E" },
    { name: "Charcoal Blue", value: "#36454F" },
    { name: "Dark Blue Grey", value: "#29465B" },
    { name: "Dark Slate", value: "#2B3856" },
    { name: "Deep-Sea Blue", value: "#123456" },
    { name: "Night Blue", value: "#151B54" },
    { name: "MidnightBlue (W3C)", value: "#191970" },
    { name: "Navy (W3C)", value: "#000080" },
    { name: "Denim Dark Blue", value: "#151B8D" },
    { name: "DarkBlue (W3C)", value: "#00008B" },
    { name: "Lapis Blue", value: "#15317E" },
    { name: "New Midnight Blue", value: "#0000A0" },
    { name: "Earth Blue", value: "#0000A5" },
    { name: "Cobalt Blue", value: "#0020C2" },
    { name: "MediumBlue (W3C)", value: "#0000CD" },
    { name: "Blueberry Blue", value: "#0041C2" },
    { name: "Canary Blue", value: "#2916F5" },
    { name: "Blue (W3C)", value: "#0000FF" },
    { name: "Samco Blue", value: "#0002FF" },
    { name: "Bright Blue", value: "#0909FF" },
    { name: "Blue Orchid", value: "#1F45FC" },
    { name: "Sapphire Blue", value: "#2554C7" },
    { name: "Blue Eyes", value: "#1569C7" },
    { name: "Bright Navy Blue", value: "#1974D2" },
    { name: "Balloon Blue", value: "#2B60DE" },
    { name: "RoyalBlue (W3C)", value: "#4169E1" },
    { name: "Ocean Blue", value: "#2B65EC" },
    { name: "Blue Ribbon", value: "#306EFF" },
    { name: "Blue Dress", value: "#157DEC" },
    { name: "Neon Blue", value: "#1589FF" },
    { name: "DodgerBlue (W3C)", value: "#1E90FF" },
    { name: "Glacial Blue Ice", value: "#368BC1" },
    { name: "SteelBlue (W3C)", value: "#4682B4" },
    { name: "Silk Blue", value: "#488AC7" },
    { name: "Windows Blue", value: "#357EC7" },
    { name: "Blue Ivy", value: "#3090C7" },
    { name: "Blue Koi", value: "#659EC7" },
    { name: "Columbia Blue", value: "#87AFC7" },
    { name: "Baby Blue", value: "#95B9C7" },
    { name: "CornflowerBlue (W3C)", value: "#6495ED" },
    { name: "Sky Blue Dress", value: "#6698FF" },
    { name: "Iceberg", value: "#56A5EC" },
    { name: "Butterfly Blue", value: "#38ACEC" },
    { name: "DeepSkyBlue (W3C)", value: "#00BFFF" },
    { name: "Midday Blue", value: "#3BB9FF" },
    { name: "Crystal Blue", value: "#5CB3FF" },
    { name: "Denim Blue", value: "#79BAEC" },
    { name: "Day Sky Blue", value: "#82CAFF" },
    { name: "LightSkyBlue (W3C)", value: "#87CEFA" },
    { name: "SkyBlue (W3C)", value: "#87CEEB" },
    { name: "Jeans Blue", value: "#A0CFEC" },
    { name: "Blue Angel", value: "#B7CEEC" },
    { name: "Pastel Blue", value: "#B4CFEC" },
    { name: "Light Day Blue", value: "#ADDFFF" },
    { name: "Sea Blue", value: "#C2DFFF" },
    { name: "Heavenly Blue", value: "#C6DEFF" },
    { name: "Robin Egg Blue", value: "#BDEDFF" },
    { name: "PowderBlue (W3C)", value: "#B0E0E6" },
    { name: "Coral Blue", value: "#AFDCEC" },
    { name: "LightBlue (W3C)", value: "#ADD8E6" },
    { name: "LightSteelBlue (W3C)", value: "#B0CFDE" },
    { name: "Gulf Blue", value: "#C9DFEC" },
    { name: "Pastel Light Blue", value: "#D5D6EA" },
    { name: "Lavender Blue", value: "#E3E4FA" },
    { name: "White Blue", value: "#DBE9FA" },
    { name: "Lavender (W3C)", value: "#E6E6FA" },
    { name: "Water", value: "#EBF4FA" },
    { name: "AliceBlue (W3C)", value: "#F0F8FF" },
    { name: "GhostWhite (W3C)", value: "#F8F8FF" },
    { name: "Azure (W3C)", value: "#F0FFFF" },
    { name: "LightCyan (W3C)", value: "#E0FFFF" },
    { name: "Light Slate", value: "#CCFFFF" },
    { name: "Electric Blue", value: "#9AFEFF" },
    { name: "Tron Blue", value: "#7DFDFE" },
    { name: "Blue Zircon", value: "#57FEFF" },
    { name: "Aqua or Cyan (W3C)", value: "#00FFFF" },
    { name: "Bright Cyan", value: "#0AFFFF" },
    { name: "Celeste", value: "#50EBEC" },
    { name: "Blue Diamond", value: "#4EE2EC" },
    { name: "Bright Turquoise", value: "#16E2F5" },
    { name: "Blue Lagoon", value: "#8EEBEC" },
    { name: "PaleTurquoise (W3C)", value: "#AFEEEE" },
    { name: "Pale Blue Lily", value: "#CFECEC" },
    { name: "Light Teal", value: "#B3D9D9" },
    { name: "Tiffany Blue", value: "#81D8D0" },
    { name: "Blue Hosta", value: "#77BFC7" },
    { name: "Cyan Opaque", value: "#92C7C7" },
    { name: "Northern Lights Blue", value: "#78C7C7" },
    { name: "Blue Green", value: "#7BCCB5" },
    { name: "MediumAquaMarine (W3C)", value: "#66CDAA" },
    { name: "Magic Mint", value: "#AAF0D1" },
    { name: "Light Aquamarine", value: "#93FFE8" },
    { name: "Aquamarine (W3C)", value: "#7FFFD4" },
    { name: "Bright Teal", value: "#01F9C6" },
    { name: "Turquoise (W3C)", value: "#40E0D0" },
    { name: "MediumTurquoise (W3C)", value: "#48D1CC" },
    { name: "Deep Turquoise", value: "#48CCCD" },
    { name: "Jellyfish", value: "#46C7C7" },
    { name: "Blue Turquoise", value: "#43C6DB" },
    { name: "DarkTurquoise (W3C)", value: "#00CED1" },
    { name: "Macaw Blue Green", value: "#43BFC7" },
    { name: "LightSeaGreen (W3C)", value: "#20B2AA" },
    { name: "Seafoam Green", value: "#3EA99F" },
    { name: "CadetBlue (W3C)", value: "#5F9EA0" },
    { name: "Deep-Sea", value: "#3B9C9C" },
    { name: "DarkCyan (W3C)", value: "#008B8B" },
    { name: "Teal Green", value: "#00827F" },
    { name: "Teal (W3C)", value: "#008080" },
    { name: "Teal Blue", value: "#007C80" },
    { name: "Medium Teal", value: "#045F5F" },
    { name: "Dark Teal", value: "#045D5D" },
    { name: "Deep Teal", value: "#033E3E" },
    { name: "DarkSlateGray or DarkSlateGrey (W3C)", value: "#25383C" },
    { name: "Gunmetal", value: "#2C3539" },
    { name: "Blue Moss Green", value: "#3C565B" },
    { name: "Beetle Green", value: "#4C787E" },
    { name: "Grayish Turquoise", value: "#5E7D7E" },
    { name: "Greenish Blue", value: "#307D7E" },
    { name: "Aquamarine Stone", value: "#348781" },
    { name: "Sea Turtle Green", value: "#438D80" },
    { name: "Dull-Sea Green", value: "#4E8975" },
    { name: "Dark Green Blue", value: "#1F6357" },
    { name: "Deep-Sea Green", value: "#306754" },
    { name: "Bottle Green", value: "#006A4E" },
    { name: "SeaGreen (W3C)", value: "#2E8B57" },
    { name: "Elf Green", value: "#1B8A6B" },
    { name: "Dark Mint", value: "#31906E" },
    { name: "Jade", value: "#00A36C" },
    { name: "Earth Green", value: "#34A56F" },
    { name: "Chrome Green", value: "#1AA260" },
    { name: "Emerald", value: "#50C878" },
    { name: "Mint", value: "#3EB489" },
    { name: "MediumSeaGreen (W3C)", value: "#3CB371" },
    { name: "Metallic Green", value: "#7C9D8E" },
    { name: "Camouflage Green", value: "#78866B" },
    { name: "Sage Green", value: "#848B79" },
    { name: "Hazel Green", value: "#617C58" },
    { name: "Venom Green", value: "#728C00" },
    { name: "OliveDrab (W3C)", value: "#6B8E23" },
    { name: "Olive (W3C)", value: "#808000" },
    { name: "DarkOliveGreen (W3C)", value: "#556B2F" },
    { name: "Military Green", value: "#4E5B31" },
    { name: "Green Leaves", value: "#3A5F0B" },
    { name: "Army Green", value: "#4B5320" },
    { name: "Fern Green", value: "#667C26" },
    { name: "Fall Forest Green", value: "#4E9258" },
    { name: "Irish Green", value: "#08A04B" },
    { name: "Pine Green", value: "#387C44" },
    { name: "Medium Forest Green", value: "#347235" },
    { name: "Jungle Green", value: "#347C2C" },
    { name: "Cactus Green", value: "#227442" },
    { name: "ForestGreen (W3C)", value: "#228B22" },
    { name: "Green (W3C)", value: "#008000" },
    { name: "DarkGreen (W3C)", value: "#006400" },
    { name: "Deep Green", value: "#056608" },
    { name: "Deep Emerald Green", value: "#046307" },
    { name: "Hunter Green", value: "#355E3B" },
    { name: "Dark Forest Green", value: "#254117" },
    { name: "Lotus Green", value: "#004225" },
    { name: "Seaweed Green", value: "#437C17" },
    { name: "Shamrock Green", value: "#347C17" },
    { name: "Green Onion", value: "#6AA121" },
    { name: "Moss Green", value: "#8A9A5B" },
    { name: "Grass Green", value: "#3F9B0B" },
    { name: "Green Pepper", value: "#4AA02C" },
    { name: "Dark Lime Green", value: "#41A317" },
    { name: "Parrot Green", value: "#12AD2B" },
    { name: "Clover Green", value: "#3EA055" },
    { name: "Dinosaur Green", value: "#73A16C" },
    { name: "Green Snake", value: "#6CBB3C" },
    { name: "Alien Green", value: "#6CC417" },
    { name: "Green Apple", value: "#4CC417" },
    { name: "LimeGreen (W3C)", value: "#32CD32" },
    { name: "Pea Green", value: "#52D017" },
    { name: "Kelly Green", value: "#4CC552" },
    { name: "Zombie Green", value: "#54C571" },
    { name: "Green Peas", value: "#89C35C" },
    { name: "Dollar Bill Green", value: "#85BB65" },
    { name: "Frog Green", value: "#99C68E" },
    { name: "Turquoise Green", value: "#A0D6B4" },
    { name: "DarkSeaGreen (W3C)", value: "#8FBC8F" },
    { name: "Basil Green", value: "#829F82" },
    { name: "Gray Green", value: "#A2AD9C" },
    { name: "Iguana Green", value: "#9CB071" },
    { name: "Citron Green", value: "#8FB31D" },
    { name: "Acid Green", value: "#B0BF1A" },
    { name: "Avocado Green", value: "#B2C248" },
    { name: "Pistachio Green", value: "#9DC209" },
    { name: "Salad Green", value: "#A1C935" },
    { name: "YellowGreen (W3C)", value: "#9ACD32" },
    { name: "Pastel Green", value: "#77DD77" },
    { name: "Hummingbird Green", value: "#7FE817" },
    { name: "Nebula Green", value: "#59E817" },
    { name: "Stoplight Go Green", value: "#57E964" },
    { name: "Neon Green", value: "#16F529" },
    { name: "Jade Green", value: "#5EFB6E" },
    { name: "Lime Mint Green", value: "#36F57F" },
    { name: "SpringGreen (W3C)", value: "#00FF7F" },
    { name: "MediumSpringGreen (W3C)", value: "#00FA9A" },
    { name: "Emerald Green", value: "#5FFB17" },
    { name: "Lime (W3C)", value: "#00FF00" },
    { name: "LawnGreen (W3C)", value: "#7CFC00" },
    { name: "Bright Green", value: "#66FF00" },
    { name: "Chartreuse (W3C)", value: "#7FFF00" },
    { name: "Yellow Lawn Green", value: "#87F717" },
    { name: "Aloe Vera Green", value: "#98F516" },
    { name: "Dull Green Yellow", value: "#B1FB17" },
    { name: "Lemon Green", value: "#ADF802" },
    { name: "GreenYellow (W3C)", value: "#ADFF2F" },
    { name: "Chameleon Green", value: "#BDF516" },
    { name: "Neon Yellow Green", value: "#DAEE01" },
    { name: "Yellow Green Grosbeak", value: "#E2F516" },
    { name: "Tea Green", value: "#CCFB5D" },
    { name: "Slime Green", value: "#BCE954" },
    { name: "Algae Green", value: "#64E986" },
    { name: "LightGreen (W3C)", value: "#90EE90" },
    { name: "Dragon Green", value: "#6AFB92" },
    { name: "PaleGreen (W3C)", value: "#98FB98" },
    { name: "Mint Green", value: "#98FF98" },
    { name: "Green Thumb", value: "#B5EAAA" },
    { name: "Organic Brown", value: "#E3F9A6" },
    { name: "Light Jade", value: "#C3FDB8" },
    { name: "Light Mint Green", value: "#C2E5D3" },
    { name: "Light Rose Green", value: "#DBF9DB" },
    { name: "Chrome White", value: "#E8F1D4" },
    { name: "HoneyDew (W3C)", value: "#F0FFF0" },
    { name: "MintCream (W3C)", value: "#F5FFFA" },
    { name: "LemonChiffon (W3C)", value: "#FFFACD" },
    { name: "Parchment", value: "#FFFFC2" },
    { name: "Cream", value: "#FFFFCC" },
    { name: "Cream White", value: "#FFFDD0" },
    { name: "LightGoldenRodYellow (W3C)", value: "#FAFAD2" },
    { name: "LightYellow (W3C)", value: "#FFFFE0" },
    { name: "Beige (W3C)", value: "#F5F5DC" },
    { name: "Cornsilk (W3C)", value: "#FFF8DC" },
    { name: "Blonde", value: "#FBF6D9" },
    { name: "Champagne", value: "#F7E7CE" },
    { name: "AntiqueWhite (W3C)", value: "#FAEBD7" },
    { name: "PapayaWhip (W3C)", value: "#FFEFD5" },
    { name: "BlanchedAlmond (W3C)", value: "#FFEBCD" },
    { name: "Bisque (W3C)", value: "#FFE4C4" },
    { name: "Wheat (W3C)", value: "#F5DEB3" },
    { name: "Moccasin (W3C)", value: "#FFE4B5" },
    { name: "Peach", value: "#FFE5B4" },
    { name: "Light Orange", value: "#FED8B1" },
    { name: "PeachPuff (W3C)", value: "#FFDAB9" },
    { name: "Coral Peach", value: "#FBD5AB" },
    { name: "NavajoWhite (W3C)", value: "#FFDEAD" },
    { name: "Golden Blonde", value: "#FBE7A1" },
    { name: "Golden Silk", value: "#F3E3C3" },
    { name: "Dark Blonde", value: "#F0E2B6" },
    { name: "Light Gold", value: "#F1E5AC" },
    { name: "Vanilla", value: "#F3E5AB" },
    { name: "Tan Brown", value: "#ECE5B6" },
    { name: "Dirty White", value: "#E8E4C9" },
    { name: "PaleGoldenRod (W3C)", value: "#EEE8AA" },
    { name: "Khaki (W3C)", value: "#F0E68C" },
    { name: "Cardboard Brown", value: "#EDDA74" },
    { name: "Harvest Gold", value: "#EDE275" },
    { name: "Sun Yellow", value: "#FFE87C" },
    { name: "Corn Yellow", value: "#FFF380" },
    { name: "Pastel Yellow", value: "#FAF884" },
    { name: "Neon Yellow", value: "#FFFF33" },
    { name: "Yellow (W3C)", value: "#FFFF00" },
    { name: "Canary Yellow", value: "#FFEF00" },
    { name: "Banana Yellow", value: "#F5E216" },
    { name: "Mustard Yellow", value: "#FFDB58" },
    { name: "Golden Yellow", value: "#FFDF00" },
    { name: "Bold Yellow", value: "#F9DB24" },
    { name: "Rubber Ducky Yellow", value: "#FFD801" },
    { name: "Gold (W3C)", value: "#FFD700" },
    { name: "Bright Gold", value: "#FDD017" },
    { name: "Chrome Gold", value: "#FFCE44" },
    { name: "Golden Brown", value: "#EAC117" },
    { name: "Deep Yellow", value: "#F6BE00" },
    { name: "Macaroni and Cheese", value: "#F2BB66" },
    { name: "Saffron", value: "#FBB917" },
    { name: "Neon Gold", value: "#FDBD01" },
    { name: "Beer", value: "#FBB117" },
    { name: "Yellow Orange or Orange Yellow", value: "#FFAE42" },
    { name: "Cantaloupe", value: "#FFA62F" },
    { name: "Cheese Orange", value: "#FFA600" },
    { name: "Orange (W3C)", value: "#FFA500" },
    { name: "Brown Sand", value: "#EE9A4D" },
    { name: "SandyBrown (W3C)", value: "#F4A460" },
    { name: "Brown Sugar", value: "#E2A76F" },
    { name: "Camel Brown", value: "#C19A6B" },
    { name: "Deer Brown", value: "#E6BF83" },
    { name: "BurlyWood (W3C)", value: "#DEB887" },
    { name: "Tan (W3C)", value: "#D2B48C" },
    { name: "Light French Beige", value: "#C8AD7F" },
    { name: "Sand", value: "#C2B280" },
    { name: "Sage", value: "#BCB88A" },
    { name: "Fall Leaf Brown", value: "#C8B560" },
    { name: "Ginger Brown", value: "#C9BE62" },
    { name: "Bronze Gold", value: "#C9AE5D" },
    { name: "DarkKhaki (W3C)", value: "#BDB76B" },
    { name: "Olive Green", value: "#BAB86C" },
    { name: "Brass", value: "#B5A642" },
    { name: "Cookie Brown", value: "#C7A317" },
    { name: "Metallic Gold", value: "#D4AF37" },
    { name: "Bee Yellow", value: "#E9AB17" },
    { name: "School Bus Yellow", value: "#E8A317" },
    { name: "GoldenRod (W3C)", value: "#DAA520" },
    { name: "Orange Gold", value: "#D4A017" },
    { name: "Caramel", value: "#C68E17" },
    { name: "DarkGoldenRod (W3C)", value: "#B8860B" },
    { name: "Cinnamon", value: "#C58917" },
    { name: "Peru (W3C)", value: "#CD853F" },
    { name: "Bronze", value: "#CD7F32" },
    { name: "Tiger Orange", value: "#C88141" },
    { name: "Copper", value: "#B87333" },
    { name: "Dark Gold", value: "#AA6C39" },
    { name: "Metallic Bronze", value: "#A97142" },
    { name: "Dark Almond", value: "#AB784E" },
    { name: "Wood", value: "#966F33" },
    { name: "Oak Brown", value: "#806517" },
    { name: "Antique Bronze", value: "#665D1E" },
    { name: "Hazel", value: "#8E7618" },
    { name: "Dark Yellow", value: "#8B8000" },
    { name: "Dark Moccasin", value: "#827839" },
    { name: "Khaki Green", value: "#8A865D" },
    { name: "Millennium Jade", value: "#93917C" },
    { name: "Dark Beige", value: "#9F8C76" },
    { name: "Bullet Shell", value: "#AF9B60" },
    { name: "Army Brown", value: "#827B60" },
    { name: "Sandstone", value: "#786D5F" },
    { name: "Taupe", value: "#483C32" },
    { name: "Mocha", value: "#493D26" },
    { name: "Milk Chocolate", value: "#513B1C" },
    { name: "Gray Brown", value: "#3D3635" },
    { name: "Dark Coffee", value: "#3B2F2F" },
    { name: "Old Burgundy", value: "#43302E" },
    { name: "Western Charcoal", value: "#49413F" },
    { name: "Bakers Brown", value: "#5C3317" },
    { name: "Dark Brown", value: "#654321" },
    { name: "Sepia Brown", value: "#704214" },
    { name: "Dark Bronze", value: "#804A00" },
    { name: "Coffee", value: "#6F4E37" },
    { name: "Brown Bear", value: "#835C3B" },
    { name: "Red Dirt", value: "#7F5217" },
    { name: "Sepia", value: "#7F462C" },
    { name: "Sienna (W3C)", value: "#A0522D" },
    { name: "SaddleBrown (W3C)", value: "#8B4513" },
    { name: "Dark Sienna", value: "#8A4117" },
    { name: "Sangria", value: "#7E3817" },
    { name: "Blood Red", value: "#7E3517" },
    { name: "Chestnut", value: "#954535" },
    { name: "Coral Brown", value: "#9E4638" },
    { name: "Chestnut Red", value: "#C34A2C" },
    { name: "Mahogany", value: "#C04000" },
    { name: "Red Gold", value: "#EB5406" },
    { name: "Red Fox", value: "#C35817" },
    { name: "Dark Bisque", value: "#B86500" },
    { name: "Light Brown", value: "#B5651D" },
    { name: "Petra Gold", value: "#B76734" },
    { name: "Rust", value: "#C36241" },
    { name: "Copper Red", value: "#CB6D51" },
    { name: "Orange Salmon", value: "#C47451" },
    { name: "Chocolate (W3C)", value: "#D2691E" },
    { name: "Sedona", value: "#CC6600" },
    { name: "Papaya Orange", value: "#E56717" },
    { name: "Halloween Orange", value: "#E66C2C" },
    { name: "Neon Orange", value: "#FF6700" },
    { name: "Bright Orange", value: "#FF5F1F" },
    { name: "Pumpkin Orange", value: "#F87217" },
    { name: "Carrot Orange", value: "#F88017" },
    { name: "DarkOrange (W3C)", value: "#FF8C00" },
    { name: "Construction Cone Orange", value: "#F87431" },
    { name: "Indian Saffron", value: "#FF7722" },
    { name: "Sunrise Orange", value: "#E67451" },
    { name: "Mango Orange", value: "#FF8040" },
    { name: "Coral (W3C)", value: "#FF7F50" },
    { name: "Basket Ball Orange", value: "#F88158" },
    { name: "Light Salmon Rose", value: "#F9966B" },
    { name: "LightSalmon (W3C)", value: "#FFA07A" },
    { name: "DarkSalmon (W3C)", value: "#E9967A" },
    { name: "Tangerine", value: "#E78A61" },
    { name: "Light Copper", value: "#DA8A67" },
    { name: "Salmon Pink", value: "#FF8674" },
    { name: "Salmon (W3C)", value: "#FA8072" },
    { name: "Peach Pink", value: "#F98B88" },
    { name: "LightCoral (W3C)", value: "#F08080" },
    { name: "Pastel Red", value: "#F67280" },
    { name: "Pink Coral", value: "#E77471" },
    { name: "Bean Red", value: "#F75D59" },
    { name: "Valentine Red", value: "#E55451" },
    { name: "IndianRed (W3C)", value: "#CD5C5C" },
    { name: "Tomato (W3C)", value: "#FF6347" },
    { name: "Shocking Orange", value: "#E55B3C" },
    { name: "OrangeRed (W3C)", value: "#FF4500" },
    { name: "Red (W3C)", value: "#FF0000" },
    { name: "Neon Red", value: "#FD1C03" },
    { name: "Scarlet Red", value: "#FF2400" },
    { name: "Ruby Red", value: "#F62217" },
    { name: "Ferrari Red", value: "#F70D1A" },
    { name: "Fire Engine Red", value: "#F62817" },
    { name: "Lava Red", value: "#E42217" },
    { name: "Love Red", value: "#E41B17" },
    { name: "Grapefruit", value: "#DC381F" },
    { name: "Cherry Red", value: "#C24641" },
    { name: "Chilli Pepper", value: "#C11B17" },
    { name: "FireBrick (W3C)", value: "#B22222" },
    { name: "Tomato Sauce Red", value: "#B21807" },
    { name: "Brown (W3C)", value: "#A52A2A" },
    { name: "Carbon Red", value: "#A70D2A" },
    { name: "Cranberry", value: "#9F000F" },
    { name: "Saffron Red", value: "#931314" },
    { name: "Crimson Red", value: "#990000" },
    { name: "Red Wine or Wine Red", value: "#990012" },
    { name: "DarkRed (W3C)", value: "#8B0000" },
    { name: "Maroon (W3C)", value: "#800000" },
    { name: "Burgundy", value: "#8C001A" },
    { name: "Vermilion", value: "#7E191B" },
    { name: "Deep Red", value: "#800517" },
    { name: "Red Blood", value: "#660000" },
    { name: "Blood Night", value: "#551606" },
    { name: "Dark Scarlet", value: "#560319" },
    { name: "Black Bean", value: "#3D0C02" },
    { name: "Chocolate Brown", value: "#3F000F" },
    { name: "Midnight", value: "#2B1B17" },
    { name: "Purple Lily", value: "#550A35" },
    { name: "Purple Maroon", value: "#810541" },
    { name: "Plum Pie", value: "#7D0541" },
    { name: "Plum Velvet", value: "#7D0552" },
    { name: "Dark Raspberry", value: "#872657" },
    { name: "Velvet Maroon", value: "#7E354D" },
    { name: "Rosy-Finch", value: "#7F4E52" },
    { name: "Dull Purple", value: "#7F525D" },
    { name: "Puce", value: "#7F5A58" },
    { name: "Rose Dust", value: "#997070" },
    { name: "Pastel Brown", value: "#B1907F" },
    { name: "Rosy Pink", value: "#B38481" },
    { name: "RosyBrown (W3C)", value: "#BC8F8F" },
    { name: "Khaki Rose", value: "#C5908E" },
    { name: "Lipstick Pink", value: "#C48793" },
    { name: "Pink Brown", value: "#C48189" },
    { name: "Old Rose", value: "#C08081" },
    { name: "Dusty Pink", value: "#D58A94" },
    { name: "Pink Daisy", value: "#E799A3" },
    { name: "Rose", value: "#E8ADAA" },
    { name: "Dusty Rose", value: "#C9A9A6" },
    { name: "Silver Pink", value: "#C4AEAD" },
    { name: "Gold Pink", value: "#E6C7C2" },
    { name: "Rose Gold", value: "#ECC5C0" },
    { name: "Deep Peach", value: "#FFCBA4" },
    { name: "Pastel Orange", value: "#F8B88B" },
    { name: "Desert Sand", value: "#EDC9AF" },
    { name: "Unbleached Silk", value: "#FFDDCA" },
    { name: "Pig Pink", value: "#FDD7E4" },
    { name: "Pale Pink", value: "#F2D4D7" },
    { name: "Blush", value: "#FFE6E8" },
    { name: "MistyRose (W3C)", value: "#FFE4E1" },
    { name: "Pink Bubble Gum", value: "#FFDFDD" },
    { name: "Light Rose", value: "#FBCFCD" },
    { name: "Light Red", value: "#FFCCCB" },
    { name: "Warm Pink", value: "#F6C6BD" },
    { name: "Deep Rose", value: "#FBBBB9" },
    { name: "Pink (W3C)", value: "#FFC0CB" },
    { name: "LightPink (W3C)", value: "#FFB6C1" },
    { name: "Soft Pink", value: "#FFB8BF" },
    { name: "Donut Pink", value: "#FAAFBE" },
    { name: "Baby Pink", value: "#FAAFBA" },
    { name: "Flamingo Pink", value: "#F9A7B0" },
    { name: "Pastel Pink", value: "#FEA3AA" },
    { name: "Rose Pink or Pink Rose", value: "#E7A1B0" },
    { name: "Cadillac Pink", value: "#E38AAE" },
    { name: "Carnation Pink", value: "#F778A1" },
    { name: "Pastel Rose", value: "#E5788F" },
    { name: "Blush Red", value: "#E56E94" },
    { name: "PaleVioletRed (W3C)", value: "#DB7093" },
    { name: "Purple Pink", value: "#D16587" },
    { name: "Tulip Pink", value: "#C25A7C" },
    { name: "Bashful Pink", value: "#C25283" },
    { name: "Dark Pink", value: "#E75480" },
    { name: "Dark Hot Pink", value: "#F660AB" },
    { name: "HotPink (W3C)", value: "#FF69B4" },
    { name: "Watermelon Pink", value: "#FC6C85" },
    { name: "Violet Red", value: "#F6358A" },
    { name: "Hot Deep Pink", value: "#F52887" },
    { name: "Bright Pink", value: "#FF007F" },
    { name: "DeepPink (W3C)", value: "#FF1493" },
    { name: "Neon Pink", value: "#F535AA" },
    { name: "Chrome Pink", value: "#FF33AA" },
    { name: "Neon Hot Pink", value: "#FD349C" },
    { name: "Pink Cupcake", value: "#E45E9D" },
    { name: "Royal Pink", value: "#E759AC" },
    { name: "Dimorphotheca Magenta", value: "#E3319D" },
    { name: "Pink Lemonade", value: "#E4287C" },
    { name: "Red Pink", value: "#FA2A55" },
    { name: "Raspberry", value: "#E30B5D" },
    { name: "Crimson (W3C)", value: "#DC143C" },
    { name: "Bright Maroon", value: "#C32148" },
    { name: "Rose Red", value: "#C21E56" },
    { name: "Rogue Pink", value: "#C12869" },
    { name: "Burnt Pink", value: "#C12267" },
    { name: "Pink Violet", value: "#CA226B" },
    { name: "Magenta Pink", value: "#CC338B" },
    { name: "MediumVioletRed (W3C)", value: "#C71585" },
    { name: "Dark Carnation Pink", value: "#C12283" },
    { name: "Raspberry Purple", value: "#B3446C" },
    { name: "Pink Plum", value: "#B93B8F" },
    { name: "Orchid (W3C)", value: "#DA70D6" },
    { name: "Deep Mauve", value: "#DF73D4" },
    { name: "Violet (W3C)", value: "#EE82EE" },
    { name: "Fuchsia Pink", value: "#FF77FF" },
    { name: "Bright Neon Pink", value: "#F433FF" },
    { name: "Fuchsia or Magenta (W3C)", value: "#FF00FF" },
    { name: "Crimson Purple", value: "#E238EC" },
    { name: "Heliotrope Purple", value: "#D462FF" },
    { name: "Tyrian Purple", value: "#C45AEC" },
    { name: "MediumOrchid (W3C)", value: "#BA55D3" },
    { name: "Purple Flower", value: "#A74AC7" },
    { name: "Orchid Purple", value: "#B048B5" },
    { name: "Rich Lilac", value: "#B666D2" },
    { name: "Pastel Violet", value: "#D291BC" },
    { name: "Mauve Taupe", value: "#915F6D" },
    { name: "Viola Purple", value: "#7E587E" },
    { name: "Eggplant", value: "#614051" },
    { name: "Plum Purple", value: "#583759" },
    { name: "Grape", value: "#5E5A80" },
    { name: "Purple Navy", value: "#4E5180" },
    { name: "SlateBlue (W3C)", value: "#6A5ACD" },
    { name: "Blue Lotus", value: "#6960EC" },
    { name: "Blurple", value: "#5865F2" },
    { name: "Light Slate Blue", value: "#736AFF" },
    { name: "MediumSlateBlue (W3C)", value: "#7B68EE" },
    { name: "Periwinkle Purple", value: "#7575CF" },
    { name: "Very Peri", value: "#6667AB" },
    { name: "Bright Grape", value: "#6F2DA8" },
    { name: "Purple Amethyst", value: "#6C2DC7" },
    { name: "Bright Purple", value: "#6A0DAD" },
    { name: "Deep Periwinkle", value: "#5453A6" },
    { name: "DarkSlateBlue (W3C)", value: "#483D8B" },
    { name: "Purple Haze", value: "#4E387E" },
    { name: "Purple Iris", value: "#571B7E" },
    { name: "Dark Purple", value: "#4B0150" },
    { name: "Deep Purple", value: "#36013F" },
    { name: "Midnight Purple", value: "#2E1A47" },
    { name: "Purple Monster", value: "#461B7E" },
    { name: "Indigo (W3C)", value: "#4B0082" },
    { name: "Blue Whale", value: "#342D7E" },
    { name: "RebeccaPurple (W3C)", value: "#663399" },
    { name: "Purple Jam", value: "#6A287E" },
    { name: "DarkMagenta (W3C)", value: "#8B008B" },
    { name: "Purple (W3C)", value: "#800080" },
    { name: "French Lilac", value: "#86608E" },
    { name: "DarkOrchid (W3C)", value: "#9932CC" },
    { name: "DarkViolet (W3C)", value: "#9400D3" },
    { name: "Purple Violet", value: "#8D38C9" },
    { name: "Jasmine Purple", value: "#A23BEC" },
    { name: "Purple Daffodil", value: "#B041FF" },
    { name: "Clematis Violet", value: "#842DCE" },
    { name: "BlueViolet (W3C)", value: "#8A2BE2" },
    { name: "Purple Sage Bush", value: "#7A5DC7" },
    { name: "Lovely Purple", value: "#7F38EC" },
    { name: "Neon Purple", value: "#9D00FF" },
    { name: "Purple Plum", value: "#8E35EF" },
    { name: "Aztech Purple", value: "#893BFF" },
    { name: "MediumPurple (W3C)", value: "#9370DB" },
    { name: "Light Purple", value: "#8467D7" },
    { name: "Crocus Purple", value: "#9172EC" },
    { name: "Purple Mimosa", value: "#9E7BFF" },
    { name: "Periwinkle", value: "#CCCCFF" },
    { name: "Pale Lilac", value: "#DCD0FF" },
    { name: "Lavender Purple", value: "#967BB6" },
    { name: "Rose Purple", value: "#B09FCA" },
    { name: "Lilac", value: "#C8A2C8" },
    { name: "Mauve", value: "#E0B0FF" },
    { name: "Bright Lilac", value: "#D891EF" },
    { name: "Purple Dragon", value: "#C38EC7" },
    { name: "Plum (W3C)", value: "#DDA0DD" },
    { name: "Blush Pink", value: "#E6A9EC" },
    { name: "Pastel Purple", value: "#F2A2E8" },
    { name: "Blossom Pink", value: "#F9B7FF" },
    { name: "Wisteria Purple", value: "#C6AEC7" },
    { name: "Purple Thistle", value: "#D2B9D3" },
    { name: "Thistle (W3C)", value: "#D8BFD8" },
    { name: "Purple White", value: "#DFD3E3" },
    { name: "Periwinkle Pink", value: "#E9CFEC" },
    { name: "Cotton Candy", value: "#FCDFFF" },
    { name: "Lavender Pinocchio", value: "#EBDDE2" },
    { name: "Dark White", value: "#E1D9D1" },
    { name: "Ash White", value: "#E9E4D4" },
    { name: "White Chocolate", value: "#EDE6D6" },
    { name: "Soft Ivory", value: "#FAF0DD" },
    { name: "Off White", value: "#F8F0E3" },
    { name: "Pearl White", value: "#F8F6F0" },
    { name: "Red White", value: "#F3E8EA" },
    { name: "LavenderBlush (W3C)", value: "#FFF0F5" },
    { name: "Pearl", value: "#FDEEF4" },
    { name: "Egg Shell", value: "#FFF9E3" },
    { name: "OldLace (W3C)", value: "#FEF0E3" },
    { name: "Linen (W3C)", value: "#FAF0E6" },
    { name: "SeaShell (W3C)", value: "#FFF5EE" },
    { name: "Bone White", value: "#F9F6EE" },
    { name: "Rice", value: "#FAF5EF" },
    { name: "FloralWhite (W3C)", value: "#FFFAF0" },
    { name: "Ivory (W3C)", value: "#FFFFF0" },
    { name: "White Gold", value: "#FFFFF4" },
    { name: "Light White", value: "#FFFFF7" },
    { name: "WhiteSmoke (W3C)", value: "#F5F5F5" },
    { name: "Cotton", value: "#FBFBF9" },
    { name: "Snow (W3C)", value: "#FFFAFA" },
    { name: "Milk White", value: "#FEFCFF" },
    { name: "Half White", value: "#FFFEFA" },
    { name: "White (W3C)", value: "#FFFFFF" },
] as NamedColor[];
